name: Build on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6

      - name: Build executable with PyInstaller
        run: pyinstaller quicktrade.py --name QuickTrade --noconsole --onefile

      - name: Upload compiled .exe
        uses: actions/upload-artifact@v4
        with:
          name: QuickTrade.exe
          path: dist/QuickTrade.exe
